//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\umpo.dll
// Interface ID: 6c9b7b96-45a8-4cca-9eb3-e21ccf8b5a89
// Interface Version: 1.1
// Client Generated: 24-2-2025 13:01:05
// NtCoreLib Version: 9.0.1+c8acea22626efab11c13778c028975acdc34678f

namespace rpc_6c9b7b96_45a8_4cca_9eb3_e21ccf8b5a89_1_1
{
    
    #region Marshal Helpers
    internal sealed class _Marshal_Helper : NtCoreLib.Ndr.Marshal.NdrMarshalBufferDelegator
    {
        public _Marshal_Helper() : 
                this(new NtCoreLib.Ndr.Marshal.NdrMarshalBuffer())
        {
        }
        public _Marshal_Helper(NtCoreLib.Ndr.Marshal.INdrMarshalBuffer m) : 
                base(m)
        {
        }
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_2(sbyte[] p0, long p1)
        {
            WriteConformantArray<sbyte>(p0, p1);
        }
        public void Write_3(sbyte[] p0, long p1)
        {
            WriteConformantArray<sbyte>(p0, p1);
        }
        public void Write_4(sbyte[] p0, long p1)
        {
            WriteConformantArray<sbyte>(p0, p1);
        }
        public void Write_5(sbyte[] p0, long p1)
        {
            WriteConformantArray<sbyte>(p0, p1);
        }
        public void Write_6(sbyte[] p0, long p1)
        {
            WriteConformantArray<sbyte>(p0, p1);
        }
        public void Write_7(System.Guid[] p0, long p1)
        {
            WriteConformantArray<System.Guid>(p0, p1);
        }
        public void Write_8(System.Guid[] p0, long p1)
        {
            WriteVaryingArray<System.Guid>(p0, p1);
        }
        public void Write_9(sbyte[] p0, long p1)
        {
            WriteConformantArray<sbyte>(p0, p1);
        }
        public void Write_10(Struct_2[] p0, long p1)
        {
            WriteConformantStructArray<Struct_2>(p0, p1);
        }
    }
    internal sealed class _Unmarshal_Helper : NtCoreLib.Ndr.Marshal.NdrUnmarshalBufferDelegator
    {
        public _Unmarshal_Helper(NtCoreLib.Ndr.Marshal.INdrUnmarshalBuffer u) : 
                base(u)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public Struct_2 Read_1()
        {
            return ReadStruct<Struct_2>();
        }
        public sbyte[] Read_2()
        {
            return ReadConformantArray<sbyte>();
        }
        public sbyte[] Read_3()
        {
            return ReadConformantArray<sbyte>();
        }
        public sbyte[] Read_4()
        {
            return ReadConformantArray<sbyte>();
        }
        public sbyte[] Read_5()
        {
            return ReadConformantArray<sbyte>();
        }
        public sbyte[] Read_6()
        {
            return ReadConformantArray<sbyte>();
        }
        public System.Guid[] Read_7()
        {
            return ReadConformantArray<System.Guid>();
        }
        public System.Guid[] Read_8()
        {
            return ReadVaryingArray<System.Guid>();
        }
        public sbyte[] Read_9()
        {
            return ReadConformantArray<sbyte>();
        }
        public Struct_2[] Read_10()
        {
            return ReadConformantStructArray<Struct_2>();
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtCoreLib.Ndr.Marshal.INdrStructure
    {
        void NtCoreLib.Ndr.Marshal.INdrStructure.Marshal(NtCoreLib.Ndr.Marshal.INdrMarshalBuffer @__m)
        {
            Marshal(new _Marshal_Helper(@__m));
        }
        private void Marshal(_Marshal_Helper @__m)
        {
            @__m.WriteInt32(Member0);
            @__m.WriteEnum16(Member4);
            @__m.WriteEnum16(Member8);
            @__m.WriteEnum16(MemberC);
        }
        void NtCoreLib.Ndr.Marshal.INdrStructure.Unmarshal(NtCoreLib.Ndr.Marshal.INdrUnmarshalBuffer @__u)
        {
            Unmarshal(new _Unmarshal_Helper(@__u));
        }
        private void Unmarshal(_Unmarshal_Helper @__u)
        {
            Member0 = @__u.ReadInt32();
            Member4 = @__u.ReadEnum16();
            Member8 = @__u.ReadEnum16();
            MemberC = @__u.ReadEnum16();
        }
        int NtCoreLib.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtCoreLib.Ndr.Marshal.NdrEnum16 Member4;
        public NtCoreLib.Ndr.Marshal.NdrEnum16 Member8;
        public NtCoreLib.Ndr.Marshal.NdrEnum16 MemberC;
        public static Struct_0 CreateDefault()
        {
            return new Struct_0();
        }
        public Struct_0(int Member0, NtCoreLib.Ndr.Marshal.NdrEnum16 Member4, NtCoreLib.Ndr.Marshal.NdrEnum16 Member8, NtCoreLib.Ndr.Marshal.NdrEnum16 MemberC)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.MemberC = MemberC;
        }
    }
    public struct Struct_2 : NtCoreLib.Ndr.Marshal.INdrStructure
    {
        void NtCoreLib.Ndr.Marshal.INdrStructure.Marshal(NtCoreLib.Ndr.Marshal.INdrMarshalBuffer @__m)
        {
            Marshal(new _Marshal_Helper(@__m));
        }
        private void Marshal(_Marshal_Helper @__m)
        {
            @__m.WriteSByte(Member0);
            @__m.WriteInt64(Member8);
            @__m.WriteInt64(Member10);
        }
        void NtCoreLib.Ndr.Marshal.INdrStructure.Unmarshal(NtCoreLib.Ndr.Marshal.INdrUnmarshalBuffer @__u)
        {
            Unmarshal(new _Unmarshal_Helper(@__u));
        }
        private void Unmarshal(_Unmarshal_Helper @__u)
        {
            Member0 = @__u.ReadSByte();
            Member8 = @__u.ReadInt64();
            Member10 = @__u.ReadInt64();
        }
        int NtCoreLib.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public sbyte Member0;
        public long Member8;
        public long Member10;
        public static Struct_2 CreateDefault()
        {
            return new Struct_2();
        }
        public Struct_2(sbyte Member0, long Member8, long Member10)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtCoreLib.Win32.Rpc.Client.RpcClientBase
    {
        public Client() : 
                base("6c9b7b96-45a8-4cca-9eb3-e21ccf8b5a89", 1, 1)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper @__m)
        {
            return new _Unmarshal_Helper(SendReceiveTransport(p, @__m));
        }
        public int UmpoRpcGetPowerConfiguration(out Struct_0 p0)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            _Unmarshal_Helper @__u = SendReceive(0, @__m);
            try
            {
                p0 = @__u.Read_0();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcReadFromSystemPowerKey(System.Nullable<System.Guid> p0, System.Nullable<System.Guid> p1, System.Nullable<System.Guid> p2, System.Nullable<System.Guid> p3, sbyte p4, int p5, ref System.Nullable<int> p6, int p7, ref sbyte[] p8, int p9, out int p10, ref System.Nullable<NtCoreLib.Ndr.Marshal.NdrEnum16> p11)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p2, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p3, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteSByte(p4);
            @__m.WriteInt32(p5);
            @__m.WriteReferent(p6, new System.Action<int>(@__m.WriteInt32));
            @__m.WriteInt32(p7);
            @__m.WriteReferent(p8, new System.Action<sbyte[], long>(@__m.Write_2), p9);
            @__m.WriteInt32(p9);
            @__m.WriteReferent(p11, new System.Action<NtCoreLib.Ndr.Marshal.NdrEnum16>(@__m.WriteEnum16));
            _Unmarshal_Helper @__u = SendReceive(1, @__m);
            try
            {
                p6 = @__u.ReadReferentValue<int>(new System.Func<int>(@__u.ReadInt32), false);
                p8 = @__u.ReadReferent<sbyte[]>(new System.Func<sbyte[]>(@__u.Read_2), false);
                p10 = @__u.ReadInt32();
                p11 = @__u.ReadReferentValue<NtCoreLib.Ndr.Marshal.NdrEnum16>(new System.Func<NtCoreLib.Ndr.Marshal.NdrEnum16>(@__u.ReadEnum16), false);
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcReadProfileAlias(System.Nullable<System.Guid> p0, ref sbyte[] p1, int p2, out int p3)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<sbyte[], long>(@__m.Write_3), p2);
            @__m.WriteInt32(p2);
            _Unmarshal_Helper @__u = SendReceive(2, @__m);
            try
            {
                p1 = @__u.ReadReferent<sbyte[]>(new System.Func<sbyte[]>(@__u.Read_3), false);
                p3 = @__u.ReadInt32();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcReadFromUserPowerKey(System.Nullable<System.Guid> p0, System.Nullable<System.Guid> p1, System.Nullable<System.Guid> p2, int p3, int p4, ref sbyte[] p5, int p6, out int p7, ref System.Nullable<NtCoreLib.Ndr.Marshal.NdrEnum16> p8)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p2, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteInt32(p3);
            @__m.WriteInt32(p4);
            @__m.WriteReferent(p5, new System.Action<sbyte[], long>(@__m.Write_4), p6);
            @__m.WriteInt32(p6);
            @__m.WriteReferent(p8, new System.Action<NtCoreLib.Ndr.Marshal.NdrEnum16>(@__m.WriteEnum16));
            _Unmarshal_Helper @__u = SendReceive(3, @__m);
            try
            {
                p5 = @__u.ReadReferent<sbyte[]>(new System.Func<sbyte[]>(@__u.Read_4), false);
                p7 = @__u.ReadInt32();
                p8 = @__u.ReadReferentValue<NtCoreLib.Ndr.Marshal.NdrEnum16>(new System.Func<NtCoreLib.Ndr.Marshal.NdrEnum16>(@__u.ReadEnum16), false);
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcReadACValue(System.Nullable<System.Guid> p0, System.Nullable<System.Guid> p1, System.Nullable<System.Guid> p2, ref System.Nullable<int> p3, ref sbyte[] p4, int p5, out int p6)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p2, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p3, new System.Action<int>(@__m.WriteInt32));
            @__m.WriteReferent(p4, new System.Action<sbyte[], long>(@__m.Write_5), p5);
            @__m.WriteInt32(p5);
            _Unmarshal_Helper @__u = SendReceive(4, @__m);
            try
            {
                p3 = @__u.ReadReferentValue<int>(new System.Func<int>(@__u.ReadInt32), false);
                p4 = @__u.ReadReferent<sbyte[]>(new System.Func<sbyte[]>(@__u.Read_5), false);
                p6 = @__u.ReadInt32();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcReadDCValue(System.Nullable<System.Guid> p0, System.Nullable<System.Guid> p1, System.Nullable<System.Guid> p2, ref System.Nullable<int> p3, ref sbyte[] p4, int p5, out int p6)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p2, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p3, new System.Action<int>(@__m.WriteInt32));
            @__m.WriteReferent(p4, new System.Action<sbyte[], long>(@__m.Write_5), p5);
            @__m.WriteInt32(p5);
            _Unmarshal_Helper @__u = SendReceive(5, @__m);
            try
            {
                p3 = @__u.ReadReferentValue<int>(new System.Func<int>(@__u.ReadInt32), false);
                p4 = @__u.ReadReferent<sbyte[]>(new System.Func<sbyte[]>(@__u.Read_5), false);
                p6 = @__u.ReadInt32();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcWriteToSystemPowerKey(System.Nullable<System.Guid> p0, System.Nullable<System.Guid> p1, System.Nullable<System.Guid> p2, System.Nullable<System.Guid> p3, int p4, int p5, int p6, sbyte[] p7, int p8)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p2, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p3, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteInt32(p4);
            @__m.WriteInt32(p5);
            @__m.WriteInt32(p6);
            @__m.Write_6(NtCoreLib.Ndr.Marshal.NdrMarshalUtils.CheckNull(p7, "p7"), p8);
            @__m.WriteInt32(p8);
            _Unmarshal_Helper @__u = SendReceive(6, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcWriteToUserPowerKey(System.Nullable<System.Guid> p0, System.Nullable<System.Guid> p1, System.Nullable<System.Guid> p2, int p3, int p4, sbyte[] p5, int p6)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p2, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteInt32(p3);
            @__m.WriteInt32(p4);
            @__m.Write_4(NtCoreLib.Ndr.Marshal.NdrMarshalUtils.CheckNull(p5, "p5"), p6);
            @__m.WriteInt32(p6);
            _Unmarshal_Helper @__u = SendReceive(7, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcApplyPowerRequestOverride()
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            _Unmarshal_Helper @__u = SendReceive(8, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcApplyPowerSetting(System.Nullable<System.Guid> p0, System.Nullable<System.Guid> p1)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            _Unmarshal_Helper @__u = SendReceive(9, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcSetActiveScheme(System.Nullable<System.Guid> p0, int p1)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteInt32(p1);
            _Unmarshal_Helper @__u = SendReceive(10, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcGetActiveScheme(out System.Guid p0)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            _Unmarshal_Helper @__u = SendReceive(11, @__m);
            try
            {
                p0 = @__u.ReadGuid();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcSetActiveOverlayScheme(System.Nullable<System.Guid> p0)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            _Unmarshal_Helper @__u = SendReceive(12, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcGetActualOverlayScheme(out System.Guid p0)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            _Unmarshal_Helper @__u = SendReceive(13, @__m);
            try
            {
                p0 = @__u.ReadGuid();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcGetEffectiveOverlayScheme(out System.Guid p0)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            _Unmarshal_Helper @__u = SendReceive(14, @__m);
            try
            {
                p0 = @__u.ReadGuid();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcGetUserConfiguredOverlayScheme(sbyte p0, out System.Guid p1)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteSByte(p0);
            _Unmarshal_Helper @__u = SendReceive(15, @__m);
            try
            {
                p1 = @__u.ReadGuid();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcSetUserConfiguredOverlayScheme(sbyte p0, System.Nullable<System.Guid> p1)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteSByte(p0);
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            _Unmarshal_Helper @__u = SendReceive(16, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcGetNonEmptyProfiles(out System.Guid[] p0, int p1, out int p2)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteInt32(p1);
            _Unmarshal_Helper @__u = SendReceive(17, @__m);
            try
            {
                p0 = @__u.Read_7();
                p2 = @__u.ReadInt32();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcGetOverlaySchemes(out System.Guid[] p0, out int p1, int p2)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteInt32(p2);
            _Unmarshal_Helper @__u = SendReceive(18, @__m);
            try
            {
                p0 = @__u.Read_8();
                p1 = @__u.ReadInt32();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcRestoreDefaultScheme(System.Nullable<System.Guid> p0)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            _Unmarshal_Helper @__u = SendReceive(19, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcRestoreDefaultSchemesAll()
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            _Unmarshal_Helper @__u = SendReceive(20, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcDuplicateScheme(System.Guid p0, System.Guid p1)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteGuid(p0);
            @__m.WriteGuid(p1);
            _Unmarshal_Helper @__u = SendReceive(21, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcDeleteScheme(System.Guid p0)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteGuid(p0);
            _Unmarshal_Helper @__u = SendReceive(22, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcImportScheme(string p0, System.Guid p1)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteTerminatedString(NtCoreLib.Ndr.Marshal.NdrMarshalUtils.CheckNull(p0, "p0"));
            @__m.WriteGuid(p1);
            _Unmarshal_Helper @__u = SendReceive(23, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcReplaceDefaultPowerSchemes()
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            _Unmarshal_Helper @__u = SendReceive(24, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcLegacyEventRegisterNotification(NtCoreLib.Ndr.Marshal.NdrUInt3264 p0, string p1, int p2)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteUInt3264(p0);
            @__m.WriteTerminatedString(NtCoreLib.Ndr.Marshal.NdrMarshalUtils.CheckNull(p1, "p1"));
            @__m.WriteInt32(p2);
            _Unmarshal_Helper @__u = SendReceive(25, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcEnumerate(System.Nullable<System.Guid> p0, System.Nullable<System.Guid> p1, int p2, int p3, ref sbyte[] p4, int p5, out int p6)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteInt32(p2);
            @__m.WriteInt32(p3);
            @__m.WriteReferent(p4, new System.Action<sbyte[], long>(@__m.Write_5), p5);
            @__m.WriteInt32(p5);
            _Unmarshal_Helper @__u = SendReceive(26, @__m);
            try
            {
                p4 = @__u.ReadReferent<sbyte[]>(new System.Func<sbyte[]>(@__u.Read_5), false);
                p6 = @__u.ReadInt32();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoCleanupSettingOverride(System.Nullable<System.Guid> p0, System.Nullable<System.Guid> p1, System.Nullable<System.Guid> p2, System.Nullable<System.Guid> p3, int p4)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p2, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p3, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteInt32(p4);
            _Unmarshal_Helper @__u = SendReceive(27, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoCleanupAllSettingOverrides()
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            _Unmarshal_Helper @__u = SendReceive(28, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcRefreshProfileSettings()
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            _Unmarshal_Helper @__u = SendReceive(29, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcReadSecurityDescriptor(int p0, System.Nullable<System.Guid> p1, ref sbyte[] p2, int p3, out int p4)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteInt32(p0);
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p2, new System.Action<sbyte[], long>(@__m.Write_9), p3);
            @__m.WriteInt32(p3);
            _Unmarshal_Helper @__u = SendReceive(30, @__m);
            try
            {
                p2 = @__u.ReadReferent<sbyte[]>(new System.Func<sbyte[]>(@__u.Read_9), false);
                p4 = @__u.ReadInt32();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcWriteSecurityDescriptor(int p0, System.Nullable<System.Guid> p1, sbyte[] p2, int p3)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteInt32(p0);
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.Write_9(NtCoreLib.Ndr.Marshal.NdrMarshalUtils.CheckNull(p2, "p2"), p3);
            @__m.WriteInt32(p3);
            _Unmarshal_Helper @__u = SendReceive(31, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcSettingAccessCheck(int p0, System.Nullable<System.Guid> p1, int p2)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteInt32(p0);
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteInt32(p2);
            _Unmarshal_Helper @__u = SendReceive(32, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcCreateSetting(System.Nullable<System.Guid> p0, System.Nullable<System.Guid> p1)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            _Unmarshal_Helper @__u = SendReceive(33, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcCreatePossibleSetting(System.Nullable<System.Guid> p0, System.Nullable<System.Guid> p1, int p2)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteInt32(p2);
            _Unmarshal_Helper @__u = SendReceive(34, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcRemoveSetting(System.Nullable<System.Guid> p0, System.Nullable<System.Guid> p1)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteReferent(p0, new System.Action<System.Guid>(@__m.WriteGuid));
            @__m.WriteReferent(p1, new System.Action<System.Guid>(@__m.WriteGuid));
            _Unmarshal_Helper @__u = SendReceive(35, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoSetExpectedUserAwayIntervals(int p0, Struct_2[] p1, int p2, int p3)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteInt32(p0);
            @__m.Write_10(NtCoreLib.Ndr.Marshal.NdrMarshalUtils.CheckNull(p1, "p1"), p0);
            @__m.WriteInt32(p2);
            @__m.WriteInt32(p3);
            _Unmarshal_Helper @__u = SendReceive(36, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoClearExpectedUserAwayIntervals(int p0)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteInt32(p0);
            _Unmarshal_Helper @__u = SendReceive(37, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoGetMinUserAwayPredictionInterval(out sbyte p0)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            _Unmarshal_Helper @__u = SendReceive(38, @__m);
            try
            {
                p0 = @__u.ReadSByte();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int UmpoRpcGetAdaptiveStandbyDiagnostics(int p0, int p1, ref sbyte[] p2, int p3, out int p4)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteInt32(p0);
            @__m.WriteInt32(p1);
            @__m.WriteReferent(p2, new System.Action<sbyte[], long>(@__m.Write_9), p3);
            @__m.WriteInt32(p3);
            _Unmarshal_Helper @__u = SendReceive(39, @__m);
            try
            {
                p2 = @__u.ReadReferent<sbyte[]>(new System.Func<sbyte[]>(@__u.Read_9), false);
                p4 = @__u.ReadInt32();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
    }
    #endregion
}

